#!/bin/sh

# Create a simple html page showcasing pdf and other digital books, given a directory
# of books
# by Emad Pourhassani emad@emadp.xyz


COVERS=covers # COVERS DIRECTORY
TEMPLATE=template.html # TEMPLATE FILE
BIBLIOTHECA=bibliotheca.html # BIBLIOTHECA FILE

# Generate Book Covers using the convert command
GenerateCovers () {
  PWD=$(pwd) # Current directory
  # Check if covers directory exists, if not create it.
	if ! [ -d $COVERS ]; then
			mkdir -p $COVERS
			echo "Created covers directory."
	fi
	
  # GET PDF COVERS
  echo "-------- GENERATING PDF COVERS --------"
  find $1 -mindepth 1 -maxdepth 1 -name "*.pdf" -print0 | while IFS= read -r -d '' book;
    do
        bookname=$(basename "$book")
        echo "generating cover for $bookname"
        convert -scale '1000x1000+0+0>' -colorspace rgb -strip "$book"\[\0\] -alpha remove -alpha off "$PWD"/$COVERS/"${bookname%.pdf}"-cover.png
    done

  # GET EPUB COVERS
  echo "-------- GENERATING EPUB COVERS --------"
  find $1 -mindepth 1 -maxdepth 1 -name "*.epub" -print0 | while IFS= read -r -d '' book;
    do
        bookname=$(basename "$book")
        echo "generating cover for $bookname"
        epub-thumbnailer "$book" "$PWD"/$COVERS/"${bookname%.epub}"-cover.png 1000 &>/dev/null
    done
    


}

# Create the html page utilizing the template
GeneratePage () {
  # Check if template exists, if not throw an error and exit.
	if ! [ -f "$TEMPLATE" ]; then
			echo ""$TEMPLATE" doesn't exist."
			echo "create a working one or download the default one at https://github.com/xemadp/spxb "
			echo "refer to the README.md for more info."
      exit $?
	fi
   
  # GET TEMPLATE FOR INDIVIDUAL BOOK ENTRY
  CONTENT=$(sed -n '/\%CONTENT\ BEGIN\%/,/\%CONTENT\ END\%/{/\%CONTENT BEGIN\%/b;/\%CONTENT END\%/b;p}' "$TEMPLATE")
  
  # GENERATE "$BIBLIOTHECA"
  cat "$TEMPLATE" | sed "/\%CONTENT END\%$/q" > "$BIBLIOTHECA"

    # GENERATE BOOK LIST
  find $1 -mindepth 1 -maxdepth 1 -name "*.pdf" -o -name "*.epub" | sort -k1 | while read -r book;
  do
    bookname="$(basename "$book")"
    echo "$CONTENT" | sed -e "s|\%BOOKDIR\%|\"$book\"|" -e "s|\%COVER\%|$COVERS\/${bookname%.*}-cover.png|" -e "s/\%BOOKNAME\%/${bookname%.*}/g" >> "$BIBLIOTHECA"
  done
  
  tac "$TEMPLATE" | sed "/\%CONTENT END\%$/q" | sed "$ d" | tac >> "$BIBLIOTHECA"

  sed -i -e "/\%CONTENT BEGIN\%/,/\%CONTENT END\%/d" "$BIBLIOTHECA"

}
case $1 in
        gc|generatecovers) GenerateCovers "$2";; # Generate covers for books in given directory 
        gp|generatepage) GeneratePage "$2";; # Generates the "$BIBLIOTHECA" file for books in given directory
        b|build) GenerateCovers "$2"; GeneratePage "$2";; # Generates covers and the "$BIBLIOTHECA" file for books in given directory

        *)      printf "USAGE: spxb OPTION DIR\n"
                printf "OPTIONS:\n"
                printf "\tspxb gc DIR => generates covers from books present in the DIR directorty\n"
                printf "\tspxb gp DIR => generates "$BIBLIOTHECA" from books present in the DIR directorty\n"
                printf "\tspxb b DIR => generates covers and "$BIBLIOTHECA" from books present in the DIR directorty\n"
                printf "\tspxb supports pdfs and epub files for now.\n";;
esac
exit $?
